name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode and SDK versions
        run: |
          xcodebuild -version
          xcodebuild -showsdks

      - name: Build StagedLauncher (Debug)
        run: |
          set -euo pipefail
          xcodebuild \
            -project StagedLauncher.xcodeproj \
            -target StagedLauncher \
            -configuration Debug \
            -destination 'generic/platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build
